version: '3.8'

services:
  sonarr:
    image: docker.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../sonarr/config:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SONARR_API_KEY=${SONARR_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

  radarr:
    image: docker.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../radarr/config:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - RADARR_API_KEY=${RADARR_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

  sabnzbd:
    image: docker.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../sabnzbd/config:/config
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SABNZBD_API_KEY=${SABNZBD_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.entrypoints=http"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)"
      - "traefik.http.middlewares.sabnzbd-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sabnzbd.middlewares=sabnzbd-https-redirect"
      - "traefik.http.routers.sabnzbd-secure.entrypoints=https"
      - "traefik.http.routers.sabnzbd-secure.rule=Host(`sabnzbd.${DOMAIN}`)"
      - "traefik.http.routers.sabnzbd-secure.tls=true"
      - "traefik.http.routers.sabnzbd-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

  bazarr:
    image: docker.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../bazarr/config:/config
      - ${MEDIA_PATH}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entrypoints=http"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bazarr.middlewares=bazarr-https-redirect"
      - "traefik.http.routers.bazarr-secure.entrypoints=https"
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../jellyfin/config:/config
      - ${MEDIA_PATH}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

  ombi:
    image: docker.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../ombi/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi.entrypoints=http"
      - "traefik.http.routers.ombi.rule=Host(`ombi.${DOMAIN}`)"
      - "traefik.http.middlewares.ombi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ombi.middlewares=ombi-https-redirect"
      - "traefik.http.routers.ombi-secure.entrypoints=https"
      - "traefik.http.routers.ombi-secure.rule=Host(`ombi.${DOMAIN}`)"
      - "traefik.http.routers.ombi-secure.tls=true"
      - "traefik.http.routers.ombi-secure.tls.certresolver=cloudflare"
    env_file:
      - ../../.env

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true 