global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'sonarr'
    metrics_path: '/api/v3/metrics'
    static_configs:
      - targets: ['sonarr:8989']
    basic_auth:
      username: '${SONARR_API_KEY}'
      password: ''

  - job_name: 'radarr'
    metrics_path: '/api/v3/metrics'
    static_configs:
      - targets: ['radarr:7878']
    basic_auth:
      username: '${RADARR_API_KEY}'
      password: ''

  - job_name: 'sabnzbd'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['sabnzbd:8080']
    params:
      apikey: ['${SABNZBD_API_KEY}']

  - job_name: 'headscale'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['headscale:8080']

  - job_name: 'jellyfin'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jellyfin:8096'] 