version: '3.8'

services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../prometheus/config:/etc/prometheus
      - ../../prometheus/data:/prometheus
    environment:
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=${ADMIN_USERS}"
      - "traefik.http.routers.prometheus-secure.middlewares=prometheus-auth"
    env_file:
      - ../../.env

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../grafana/data:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - TZ=UTC
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.grafana-auth.basicauth.users=${ADMIN_USERS}"
      - "traefik.http.routers.grafana-secure.middlewares=grafana-auth"
    env_file:
      - ../../.env

  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    labels:
      - "traefik.enable=false"
    env_file:
      - ../../.env

  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../loki/config:/etc/loki
      - ../../loki/data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    labels:
      - "traefik.enable=false"

  promtail:
    image: docker.io/grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ../../promtail/config:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    labels:
      - "traefik.enable=false"

networks:
  homelab:
    name: homelab
    driver: bridge
    external: true 